<sdf version="1.5">
  <model name="human" xmlns:xacro="http://www.ros.org/wiki/xacro">
   <xacro:property name="armEffort" value="30" /> <!-- Standard value is 30 -->
    <xacro:property name="wristEffort" value="10" /> <!-- Standard value is 10 -->
    <xacro:include filename="pr2-include.xacro" />
    <!-- Controller for the pr2 arm -->
    <!-- <plugin name="pr2_arm_controller" filename="libStableControllerPlugin.dylib">    </plugin>-->



    <!-- Human -->
    <!-- TODO: These should not be needed but parameters aren't working -->
    <xacro:property name="xoffset" value="0.939280" />
    <xacro:property name="yoffset" value="-0.25" />
    <xacro:property name="zoffset" value="0" />
    <xacro:property name="prefix" value="" />
    <xacro:include filename="human-model-include.xacro"/>
    
    <!-- Virtual connecting joint -->
    <joint name="virtual_robot_human_connection" type="ball">
      <parent>r_wrist_roll_link</parent>
      <child>${prefix}left_thigh</child>
      <pose>${xoffset - 0.16828} ${yoffset + 0.062} ${0.790675 + zoffset} 0.0 0.0 0.0</pose>
      <axis> 
        <xyz>0.0 1 0.0</xyz>
      </axis>
      <axis2>
        <xyz>0.0 0.0 1.0</xyz>
      </axis2>
      <physics>
        <ode>
          <limit>
            <cfm>0.000</cfm>
            <erp>0.8</erp>
          </limit>
        </ode>
      </physics>
    </joint>
  </model>
</sdf>
