<sdf version="1.5">
  <model name="combined_human_pr2" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="pr2.nomodel.sdf" />
    <!-- Controller for the pr2 arm -->
    <plugin name="pr2_arm_controller" filename="libStableControllerPlugin.dylib">    </plugin>



    <!-- Human -->
    <!-- TODO: These should not be needed but parameters aren't working -->
    <xacro:property name="xoffset" value="0.939280" />
    <xacro:property name="yoffset" value="-0.25" />
    <xacro:property name="zoffset" value="0" />
    <xacro:property name="prefix" value="human_" />
    <xacro:include filename="human-model-include.xacro"/>
    
    <!-- Virtual connecting joint -->
    <joint name="virtual_robot_human_connection" type="ball">
      <parent>r_wrist_roll_link</parent>
      <child>${prefix}left_thigh</child>
      <pose>${xoffset} ${yoffset} ${0.826658 + zoffset} 0.0 0.0 0.0</pose>
      <axis>
        <xyz>0.0 1 0.0</xyz>
      </axis>
    </joint>
  </model>
</sdf>
